spring:
  main:
    allow-circular-references: true

  # Database configuration
  datasource:
    #    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.44.64.30:5432/dsns_bot
    username: root
    password: 2143
  jpa:
    # PotGIS configuration
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
